### ISSUE TITLE
Select a brain / main cpu

### ISSUE THREAD

**Issue by tknobi** [CoRoSoN-Kit/CoRoSoN-Kit#18]
Basically there are 2 possibilities here:

1. We build our own board, take care of power supply, programming adapters, connectivity, IDE integration, etc. ourselves. This would give us full design control.
2. We use an existing single board chip, which is tested and takes a lot of work off our shoulders, but of course costs us some flexibility.

Should we find a suitable board for solution approach 2, I would personally be strongly in favor of it. 

Therefore, here is a tabular comparison of boards which we had already considered in verbal discussion or in Discord:

*Work in progress!*
 
| Property | [Raspberry Pi Pico](https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html) | [ESP32-DevKitCVE](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-devkitc.html) | [Arduino Nano Every](https://store.arduino.cc/products/arduino-nano-every) | [WeAct Black Pill V1.2](https://stm32-base.org/boards/STM32F401CCU6-WeAct-Black-Pill-V1.2.html) | [Arduino MEGA 2560 Pro](https://www.pcboard.ca/mega-2560-pro) |
| --- | --- | --- | --- | --- | --- |
| Open Source | :heavy_check_mark: | :x: | :heavy_check_mark: | :heavy_check_mark: | :question: |
| Availability | Many [official Resellers](https://www.raspberrypi.com/products/raspberry-pi-pico/) nearly all over the world | Many suppliers (as far as I can judge from Germany) | Official worldwide Arduino Store + many resellers | Only by China Import | Not an official manufacturer, but are found in many shops. |
| Dimensions | 51 mm x 21 mm | 54.4 mm x 27.9 mm | 45 mm x 18 mm | 52.8 mm x 20.8 mm | 54 mm x 38 mm |
| Input Voltage | 1.8 V - 5.5 V | 3.3 V - 5 V | 7 V - 21 V | 3.52 V - 5.25 V | 6 V - 12 V |
| Operating Voltage | 3.3 V | 3.3 V | 5V | 3.3V | 5 V |
| Price [^price] | 4.10 € | 11.59 € | 8.80 € | ~5€ [AliExpress](https://weactstudio.aliexpress.com/) | 19,96 € |
| CPU | [RP2040](https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf) (Dual-core Arm Cortex-M0+ processor, 133 MHz) |  [ESP32-WROOM-32](https://espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf) (Dual-core, 80 - 240 Mhz) | [ATMega4809](https://content.arduino.cc/assets/Nano-Every_processor-48-pin-Data-Sheet-megaAVR-0-series-DS40002016B.pdf) (20 MHz) | [STM32F411](https://www.st.com/resource/en/datasheet/stm32f411ce.pdf) (M4 with DSP, FPU, 100 - 200Mhz) | [ATmega2560](https://ww1.microchip.com/downloads/en/devicedoc/atmel-2549-8-bit-avr-microcontroller-atmega640-1280-1281-2560-2561_datasheet.pdf) (16 MHz) |
| RAM | 264 kB | 4 MB | 6 kB | 128 kB | 8 kB |
| Flash | 2 MB | 4 MB | 48 kB | 512 kB | 256 kB |
| No of digital I/O | 26 | 32 | 20 | 40 | 70 |
| 5 V tolerant I/O | :x: | :x: | :heavy_check_mark: | :heavy_check_mark: (except PA0) | :heavy_check_mark: |
| ADC | 3x12bit | 16x12bit | 8x10bit | 1x12bit 16ch | 16x10bit |
| I²C | 2 | 2 | 1 | 3 | :question: |
| SPI | 2 | 4 | 1 | 5 | :heavy_check_mark: but how many? ||
| UART | 2 | 3 | 1 | 3 | 4 |
| PWM | 16 | :heavy_check_mark: but how many? | 5 | 11 HW timer (6x16bit, 2x32bit) | 15 |
| Programmable Buttons | :x: | :x: | :x: | 1 | :x: |
| Programmable LEDs | 1 | :x: | 1 | 1 | 1 |
| Arduino IDE integration | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark: |
| bipes.net integration | :heavy_check_mark: | :heavy_check_mark: | :x: | :x: | :x: |
| CAN | :x: | :heavy_check_mark: Two-Wire Automotive Interface (TWAI ® ), compatible with ISO11898-1 (CAN Specification 2.0) | :x: | :x: | :x: |
| Bluetooth | :x: | :heavy_check_mark: | :x: | :x: | :x: |
| WiFi | :x: | :heavy_check_mark: | :x: | :x: | :x: |

[^price]: The current (June 14, 2022) cheapest internet price I found in Germany (without shipping).

**Comment by stiebel** [comment]
No of io Pins 
This depends. We startet with a 40$ teensy once. To get more Pins we used i2c pirt expanders and multiplexers.
But with a 4$ pi pico we would instead simple use two of them.
So for lets say 12 - 24 Pins for IR Sensors is is the cheapest and easiest way to use a Single pico and make the whole circuit Board an "ir ring sensor with i2c"

**Comment by stiebel** [comment]
Please enlarge the list:
Can Bus
Bluetooth 

The esp32 does both buildin, which is its highest advantage above the pico as far as i am concerned

**Comment by stiebel** [comment]
I absolutely understand the wish for 5V tolerance, but all these modern and cheap CPUs like ESP32 and Raspberry Pi Pico are NOT 5V tolerant. So I would rather vote for a "lego-adapter" ore even a "lego-shield" to adopt to 5v envirement,
Apart from lego there is only the pixy-cam that wants to have 5V for power but has a 3.3v Level UART/SPI/I2C communication.
all other Stuff should work with 3.3v

**Comment by dbscoach** [comment]
Built-in level shifters (for some 5V-capable ports) and/or protective diodes so you don't accidentally kill the board are a completely valid substitute, I agree. I just think we should design for as much robustness as we can (within reason) - or we can just have a socketed chip/subboard because replacing a 5$ chip is a valuable learning experience in and of itself...

**Comment by tknobi** [comment]
Decision from the last discord meeting together with @f-gaul , @heikobaumann, @JBrutzi , @Alintya & @tknobi  : 
We use one (or more) single board chip(s). This is the only way we can use a modern chip without soldering SMD. Besides, these are now so established and mature that you would have no advantage to do it yourself. Let's finish the comparison table.

ToDo: 
* [ ] update decision board

**Comment by markosko** [comment]
For arduino maybe Arduino Mega PRO or Arduino Mini Pro?

**Comment by Alintya** [comment]
The mini pro is really limited in I/O.
Mega Pro on the other hand is super rich in I/O and might be worth consideration on signal-heavy components like the (ir) sensor board.

**Comment by tknobi** [comment]
> For arduino maybe Arduino Mega PRO or Arduino Mini Pro?

Thanks @markosko for your proposal! Can you share a datasheet or a product page? On the official [Arduino Pro website](https://www.arduino.cc/pro/hardware/product-family/portenta-family?id=25729177) is no Mega or Mini. Or are you talking about an unofficial version?

**Comment by markosko** [comment]
Yes, those unofficial /cloned but except of layout of pcb, pins are same

**Comment by Alintya** [comment]
Mostly updated OP for the Blackpoll board

**Comment by tknobi** [comment]
Decided in meeting with @f-gaul, @Alintya, @stiebel, @markosko and @tknobi:

We don't want boards that are just imported from China or don't have an official manufacturer. Therefore, we exclude the WeAct Black Pill and the Arduino MEGA 2560 Pro.

Of the well available remaining ones, the ESP32 is the one with the most features, but also the most expensive. So we will try the Raspberry Pi Pico. If this does not work (e.g. because only 3 ADC's we will think again about the ESP32). 

ToDo to close issue:

* [ ] update decision board
