### ISSUE TITLE
Make clear that soldering is needed

### ISSUE THREAD

**Issue by tknobi** [CoRoSoN-Kit/CoRoSoN-Kit#41]
In the last meeting it came out that it is not clear from our current concept that teams have to assemble and solder the components themselves. We should clarify that. (Thanks @JonGitti!)

**Comment by JonGitti** [comment]
> Soldering / mounting / 3D-Printing / etc. still needs to be done by the teams

You did actually clarify

**Comment by tknobi** [comment]
Oh yes, that's right, thank you. Then the issue has already been resolved.
